name: easy_food
description: A new Flutter project.

publish_to: 'none' # Prevents publishing this package publicly.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Match your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.3.0
  firebase_messaging: ^15.2.1
  shared_preferences: ^2.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/burger.png
    - assets/images/user.png
